services:
  - type: web
    name: stock-app
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /_stcore/health
    autoDeployTrigger: commit
    envVars:
      - key: gsheet_api_url
        sync: false
      - key: SHIOAJI_API_KEY
        sync: false
      - key: SHIOAJI_SECRET_KEY
        sync: false
